<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>哪吒2之魔童闹海 - 拼音配对游戏</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
            font-family: 'Microsoft YaHei', sans-serif;
        }
        
        body {
            background: linear-gradient(135deg, #1a0a1e 0%, #3a0a2e 100%);
            min-height: 100vh;
            display: flex;
            justify-content: center;
            align-items: center;
            padding: 20px;
            color: #fff;
        }
        
        .container {
            width: 100%;
            max-width: 900px;
            background: rgba(20, 5, 25, 0.85);
            border-radius: 20px;
            box-shadow: 0 10px 30px rgba(255, 20, 60, 0.3);
            border: 2px solid #ff143c;
            overflow: hidden;
            padding: 20px;
            position: relative;
        }
        
        .header {
            text-align: center;
            padding: 20px;
            margin-bottom: 20px;
            position: relative;
        }
        
        .title {
            font-size: 2.8rem;
            color: #ffde00;
            text-shadow: 0 0 10px rgba(255, 20, 60, 0.8);
            margin-bottom: 10px;
            letter-spacing: 2px;
            font-weight: bold;
            background: linear-gradient(to right, #ffde00, #ff143c);
            -webkit-background-clip: text;
            background-clip: text;
            color: transparent;
        }
        
        .subtitle {
            font-size: 1.2rem;
            color: #ff8a8a;
            margin-bottom: 20px;
        }
        
        .game-container {
            display: flex;
            flex-direction: column;
            gap: 50px;
            padding: 20px;
        }
        
        .row {
            display: flex;
            justify-content: space-around;
            align-items: center;
            position: relative;
        }
        
        .animal {
            width: 120px;
            height: 120px;
            background: rgba(255, 222, 0, 0.1);
            border-radius: 50%;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            cursor: pointer;
            transition: all 0.3s ease;
            border: 2px solid #ff143c;
            position: relative;
            z-index: 2;
        }
        
        .animal:hover {
            transform: scale(1.1);
            background: rgba(255, 222, 0, 0.2);
            box-shadow: 0 0 15px rgba(255, 20, 60, 0.7);
        }
        
        .animal.selected {
            background: rgba(255, 222, 0, 0.3);
            box-shadow: 0 0 20px rgba(255, 20, 60, 0.9);
        }
        
        .animal img {
            width: 70px;
            height: 70px;
            object-fit: contain;
        }
        
        .animal-name {
            margin-top: 5px;
            font-size: 1rem;
            color: #ffde00;
            font-weight: bold;
        }
        
        .pinyin {
            width: 100px;
            height: 60px;
            background: rgba(255, 222, 0, 0.15);
            border: 2px solid #ff8a00;
            border-radius: 10px;
            display: flex;
            justify-content: center;
            align-items: center;
            font-size: 1.8rem;
            color: #fff;
            cursor: pointer;
            transition: all 0.3s ease;
            position: relative;
            z-index: 2;
        }
        
        .pinyin:hover {
            transform: scale(1.1);
            background: rgba(255, 222, 0, 0.3);
            box-shadow: 0 0 15px rgba(255, 138, 0, 0.7);
        }
        
        .pinyin.selected {
            background: rgba(255, 222, 0, 0.3);
            box-shadow: 0 0 20px rgba(255, 138, 0, 0.9);
        }
        
        .lines {
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            pointer-events: none;
            z-index: 1;
        }
        
        .line {
            stroke: #ffde00;
            stroke-width: 3;
            stroke-dasharray: 10, 5;
        }
        
        .rules {
            background: rgba(10, 5, 15, 0.7);
            border: 1px solid #ff8a00;
            border-radius: 10px;
            padding: 20px;
            margin: 30px 0;
            color: #ffddaa;
            font-size: 1.1rem;
        }
        
        .rules h3 {
            color: #ffde00;
            text-align: center;
            margin-bottom: 15px;
            font-size: 1.5rem;
        }
        
        .rules ul {
            padding-left: 20px;
        }
        
        .rules li {
            margin-bottom: 10px;
            line-height: 1.5;
        }
        
        .score-container {
            text-align: center;
            font-size: 1.5rem;
            color: #ffde00;
            margin: 20px 0;
            padding: 15px;
            background: rgba(255, 20, 60, 0.2);
            border-radius: 10px;
            border: 1px solid #ff143c;
        }
        
        .nezhua-character {
            position: absolute;
            width: 180px;
            bottom: 20px;
            right: 20px;
            opacity: 0.7;
        }
        
        .fire {
            position: absolute;
            width: 100%;
            height: 20px;
            bottom: 0;
            left: 0;
            background: linear-gradient(to top, rgba(255, 60, 0, 0.6), transparent);
            z-index: 3;
        }
        
        @media (max-width: 768px) {
            .animal {
                width: 80px;
                height: 80px;
            }
            
            .animal img {
                width: 50px;
                height: 50px;
            }
            
            .pinyin {
                width: 70px;
                height: 50px;
                font-size: 1.4rem;
            }
            
            .title {
                font-size: 2rem;
            }
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1 class="title">哪吒2之魔童闹海</h1>
            <p class="subtitle">拼音配对游戏</p>
        </div>
        
        <div class="rules">
            <h3>Game Rules</h3>
            <ul>
                <li>The first row shows pictures of five animals: dragon, leopard, rat, tiger, ox</li>
                <li>The second row shows the pinyin of these animals: lóng, shǔ, bào, hǔ, niú</li>
                <li>Connect each picture to its corresponding pinyin by clicking on the animal first and then the pinyin</li>
                <li>Total score: 10 points (2 points for each correct match)</li>
                <li>Each wrong match will deduct 2 points</li>
                <li>You have only one chance - no restart allowed!</li>
            </ul>
        </div>
        
        <div class="score-container">
            Score: <span id="score">10</span>/10
        </div>
        
        <div class="game-container">
            <div class="row" id="animals-row">
                <div class="animal" data-animal="dragon">
                    <img src="data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><path d='M30,40 Q40,20 60,20 Q80,20 70,40 Q75,50 80,60 Q70,80 50,85 Q30,80 20,60 Q25,50 30,40 Z' fill='%2300a0ff'/><circle cx='40' cy='40' r='5' fill='white'/><circle cx='60' cy='40' r='5' fill='white'/><path d='M50,55 Q55,60 50,65 Q45,60 50,55 Z' fill='%23ff0000'/></svg>" alt="龙">
                    <div class="animal-name">龙</div>
                </div>
                <div class="animal" data-animal="leopard">
                    <img src="data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><path d='M20,40 Q30,20 70,20 Q80,40 75,60 Q70,80 50,85 Q30,80 25,60 Q20,50 20,40 Z' fill='%23ffaa00'/><circle cx='35' cy='40' r='5' fill='white'/><circle cx='65' cy='40' r='5' fill='white'/><path d='M50,55 Q55,60 50,65 Q45,60 50,55 Z' fill='%23000'/></svg>" alt="豹">
                    <div class="animal-name">豹</div>
                </div>
                <div class="animal" data-animal="rat">
                    <img src="data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><path d='M30,50 Q40,30 60,30 Q70,40 70,60 Q60,80 40,80 Q30,70 30,50 Z' fill='%23707070'/><circle cx='40' cy='45' r='4' fill='white'/><circle cx='60' cy='45' r='4' fill='white'/><path d='M50,60 Q55,65 50,70 Q45,65 50,60 Z' fill='%23ff0000'/><path d='M75,45 Q80,40 85,45 Q80,50 75,45 Z' fill='%23707070'/></svg>" alt="鼠">
                    <div class="animal-name">鼠</div>
                </div>
                <div class="animal" data-animal="tiger">
                    <img src="data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><path d='M20,40 Q30,20 70,20 Q80,40 75,60 Q70,80 50,85 Q30,80 25,60 Q20,50 20,40 Z' fill='%23ffaa00'/><circle cx='35' cy='40' r='5' fill='white'/><circle cx='65' cy='40' r='5' fill='white'/><path d='M50,55 Q55,60 50,65 Q45,60 50,55 Z' fill='%23000'/><path d='M20,30 Q15,25 20,20 Q25,25 20,30 Z' fill='%23ffaa00'/><path d='M80,30 Q85,25 80,20 Q75,25 80,30 Z' fill='%23ffaa00'/></svg>" alt="虎">
                    <div class="animal-name">虎</div>
                </div>
                <div class="animal" data-animal="ox">
                    <img src="data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><path d='M30,50 Q40,30 60,30 Q70,40 70,60 Q60,80 40,80 Q30,70 30,50 Z' fill='%23705030'/><circle cx='40' cy='45' r='4' fill='white'/><circle cx='60' cy='45' r='4' fill='white'/><path d='M50,60 Q55,65 50,70 Q45,65 50,60 Z' fill='%23000'/><path d='M25,40 Q20,35 25,30 Q30,35 25,40 Z' fill='%23705030'/><path d='M75,40 Q80,35 75,30 Q70,35 75,40 Z' fill='%23705030'/></svg>" alt="牛">
                    <div class="animal-name">牛</div>
                </div>
            </div>
            
            <div class="row" id="pinyin-row">
                <div class="pinyin" data-pinyin="shǔ">shǔ</div>
                <div class="pinyin" data-pinyin="hǔ">hǔ</div>
                <div class="pinyin" data-pinyin="lóng">lóng</div>
                <div class="pinyin" data-pinyin="niú">niú</div>
                <div class="pinyin" data-pinyin="bào">bào</div>
            </div>
            
            <svg class="lines" id="lines-svg"></svg>
        </div>
        
        <img class="nezhua-character" src="data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 200 300'><path d='M100,50 Q120,30 140,50 Q160,70 150,100 Q140,130 120,140 Q100,150 80,140 Q60,130 50,100 Q40,70 60,50 Q80,30 100,50 Z' fill='%23ff0000'/><path d='M100,150 L100,250 Q90,270 110,270 Q130,270 120,250 L120,150 Z' fill='%23ff0000'/><path d='M60,120 Q40,110 40,90 Q50,70 70,80 Q90,90 80,110 Q70,130 60,120 Z' fill='%23fff'/><path d='M140,120 Q160,110 160,90 Q150,70 130,80 Q110,90 120,110 Q130,130 140,120 Z' fill='%23fff'/><path d='M80,180 Q70,200 90,210 Q100,220 110,210 Q130,200 120,180 Z' fill='%23ffcc00'/><path d='M50,60 Q60,40 80,30' stroke='%23ffcc00' stroke-width='5' fill='none'/><path d='M150,60 Q140,40 120,30' stroke='%23ffcc00' stroke-width='5' fill='none'/></svg>" alt="哪吒">
        
        <div class="fire"></div>
    </div>

    <script>
        document.addEventListener('DOMContentLoaded', () => {
            const animalsRow = document.getElementById('animals-row');
            const pinyinRow = document.getElementById('pinyin-row');
            const linesSvg = document.getElementById('lines-svg');
            const scoreDisplay = document.getElementById('score');
            
            let selectedAnimal = null;
            let selectedPinyin = null;
            let score = 10;
            let connections = 0;
            const maxConnections = 5;
            
            // 动物与拼音的对应关系
            const animalToPinyin = {
                'dragon': 'lóng',
                'leopard': 'bào',
                'rat': 'shǔ',
                'tiger': 'hǔ',
                'ox': 'niú'
            };
            
            // 添加动物点击事件
            animalsRow.querySelectorAll('.animal').forEach(animal => {
                animal.addEventListener('click', () => {
                    if (animal.classList.contains('connected')) return;
                    
                    // 清除之前的选择
                    if (selectedAnimal) {
                        selectedAnimal.classList.remove('selected');
                    }
                    
                    // 选择当前动物
                    animal.classList.add('selected');
                    selectedAnimal = animal;
                    
                    // 如果拼音已选择，创建连线
                    if (selectedPinyin) {
                        createConnection();
                    }
                });
            });
            
            // 添加拼音点击事件
            pinyinRow.querySelectorAll('.pinyin').forEach(pinyin => {
                pinyin.addEventListener('click', () => {
                    if (pinyin.classList.contains('connected')) return;
                    
                    // 清除之前的选择
                    if (selectedPinyin) {
                        selectedPinyin.classList.remove('selected');
                    }
                    
                    // 选择当前拼音
                    pinyin.classList.add('selected');
                    selectedPinyin = pinyin;
                    
                    // 如果动物已选择，创建连线
                    if (selectedAnimal) {
                        createConnection();
                    }
                });
            });
            
            // 创建连线
            function createConnection() {
                if (!selectedAnimal || !selectedPinyin) return;
                
                // 获取位置
                const animalRect = selectedAnimal.getBoundingClientRect();
                const pinyinRect = selectedPinyin.getBoundingClientRect();
                const svgRect = linesSvg.getBoundingClientRect();
                
                const x1 = animalRect.left + animalRect.width/2 - svgRect.left;
                const y1 = animalRect.top + animalRect.height - svgRect.top;
                const x2 = pinyinRect.left + pinyinRect.width/2 - svgRect.left;
                const y2 = pinyinRect.top - svgRect.top;
                
                // 创建SVG连线
                const line = document.createElementNS('http://www.w3.org/2000/svg', 'line');
                line.setAttribute('x1', x1);
                line.setAttribute('y1', y1);
                line.setAttribute('x2', x2);
                line.setAttribute('y2', y2);
                line.setAttribute('class', 'line');
                
                // 检查答案是否正确
                const animalType = selectedAnimal.dataset.animal;
                const pinyinValue = selectedPinyin.dataset.pinyin;
                const isCorrect = animalToPinyin[animalType] === pinyinValue;
                
                // 设置线条颜色
                line.setAttribute('stroke', isCorrect ? '#00ff00' : '#ff0000');
                
                linesSvg.appendChild(line);
                
                // 标记已连接
                selectedAnimal.classList.add('connected');
                selectedPinyin.classList.add('connected');
                selectedAnimal.classList.remove('selected');
                selectedPinyin.classList.remove('selected');
                
                // 更新分数
                if (!isCorrect) {
                    score = Math.max(0, score - 2);
                    scoreDisplay.textContent = score;
                }
                
                // 重置选择
                selectedAnimal = null;
                selectedPinyin = null;
                
                // 增加连接计数
                connections++;
                
                // 检查游戏是否结束
                if (connections === maxConnections) {
                    setTimeout(() => {
                        let message;
                        if (score === 10) {
                            message = "恭喜！满分！哪吒为你骄傲！";
                        } else if (score >= 6) {
                            message = `干得好！得分：${score}/10`;
                        } else {
                            message = `加油！得分：${score}/10，下次会更好！`;
                        }
                        
                        alert(`游戏结束！\n${message}`);
                    }, 500);
                }
            }
        });
    </script>
</body>
</html>
